# Generated by Django 5.0.2 on 2024-03-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customer_state_alter_movies_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='show_time',
            field=models.CharField(choices=[('9 AM -1 PM', '9:00 AM - 1:00 PM'), ('1 PM -4 PM', '1:00 PM - 4:00 PM'), ('4 PM -7 PM', '4:00 PM - 7:00 PM'), ('7 PM -10 PM', '7:00 PM - 10:00 PM')], default='9-1', max_length=100),
        ),
        migrations.AddField(
            model_name='movies',
            name='theater_name',
            field=models.CharField(default='Default Theater', max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('T', 'Thriller'), ('R', 'Romance'), ('E', 'Entertaintment'), ('SF', 'ScienceFiction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked')], default='Pending', max_length=50),
        ),
    ]
