# Generated by Django 5.0.2 on 2024-03-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_movies_address_movies_show_time_movies_theater_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='address',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='show_time',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='theater_name',
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('E', 'Entertaintment'), ('R', 'Romance'), ('SF', 'ScienceFiction'), ('T', 'Thriller')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
