# Generated by Django 5.0.2 on 2024-03-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_movies_address_remove_movies_show_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='show_time',
            field=models.CharField(choices=[('9 AM -1 PM', '9:00 AM - 1:00 PM'), ('1 PM -4 PM', '1:00 PM - 4:00 PM'), ('4 PM -7 PM', '4:00 PM - 7:00 PM'), ('7 PM -10 PM', '7:00 PM - 10:00 PM')], default='9-1', max_length=100),
        ),
        migrations.AddField(
            model_name='movies',
            name='theater_name',
            field=models.CharField(default='Default Theater', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Maharashtra', 'Maharashtra')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('R', 'Romance'), ('E', 'Entertaintment'), ('T', 'Thriller'), ('SF', 'ScienceFiction')], max_length=50),
        ),
    ]
