# Generated by Django 5.0.3 on 2024-03-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_movies_seats_available_alter_movies_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='seats_available',
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('T', 'Thriller'), ('E', 'Entertaintment'), ('R', 'Romance'), ('SF', 'ScienceFiction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
