# Generated by Django 5.0.2 on 2024-04-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_movies_seats_available_alter_movies_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='seat_selection',
            field=models.CharField(default='Not Selected', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Goa', 'Goa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('E', 'Entertaintment'), ('T', 'Thriller'), ('SF', 'ScienceFiction'), ('R', 'Romance')], max_length=50),
        ),
    ]
