# Generated by Django 5.0.2 on 2024-04-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_movies_category_theaterticketbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theaterticketbooking',
            name='seats',
        ),
        migrations.AddField(
            model_name='theaterticketbooking',
            name='seat1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theaterticketbooking',
            name='seat10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theaterticketbooking',
            name='seat2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theaterticketbooking',
            name='seat3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theaterticketbooking',
            name='seat4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theaterticketbooking',
            name='seat5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theaterticketbooking',
            name='seat6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theaterticketbooking',
            name='seat7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theaterticketbooking',
            name='seat8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theaterticketbooking',
            name='seat9',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('T', 'Thriller'), ('SF', 'ScienceFiction'), ('R', 'Romance'), ('E', 'Entertaintment')], max_length=50),
        ),
    ]
