# Generated by Django 5.0.2 on 2024-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_theaterticketbooking_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theaterticketbooking',
            name='seat1',
        ),
        migrations.RemoveField(
            model_name='theaterticketbooking',
            name='seat10',
        ),
        migrations.RemoveField(
            model_name='theaterticketbooking',
            name='seat2',
        ),
        migrations.RemoveField(
            model_name='theaterticketbooking',
            name='seat3',
        ),
        migrations.RemoveField(
            model_name='theaterticketbooking',
            name='seat4',
        ),
        migrations.RemoveField(
            model_name='theaterticketbooking',
            name='seat5',
        ),
        migrations.RemoveField(
            model_name='theaterticketbooking',
            name='seat6',
        ),
        migrations.RemoveField(
            model_name='theaterticketbooking',
            name='seat7',
        ),
        migrations.RemoveField(
            model_name='theaterticketbooking',
            name='seat8',
        ),
        migrations.RemoveField(
            model_name='theaterticketbooking',
            name='seat9',
        ),
        migrations.AddField(
            model_name='theaterticketbooking',
            name='seat',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Maharashtra', 'Maharashtra')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('T', 'Thriller'), ('E', 'Entertaintment'), ('SF', 'ScienceFiction'), ('R', 'Romance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
