# Generated by Django 5.0.2 on 2024-03-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_movies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Maharashtra', 'Maharashtra')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('SF', 'ScienceFiction'), ('T', 'Thriller'), ('R', 'Romance'), ('E', 'Entertaintment')], max_length=50),
        ),
    ]
