# Generated by Django 5.0.2 on 2024-03-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customer_state_alter_movies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Goa', 'Goa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('R', 'Romance'), ('SF', 'ScienceFiction'), ('T', 'Thriller'), ('E', 'Entertaintment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
    ]
