# Generated by Django 5.0.2 on 2024-03-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studid', models.IntegerField()),
                ('stuname', models.CharField(max_length=20)),
                ('stuemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
